[tools]
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
delta = "latest"
difftastic = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
gitui = "latest"
go = "latest"
golangci-lint = "latest"
gping = "latest"
jj = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
lazydocker = "latest"
neovim = "latest"
node = "lts"
pnpm = "latest"
python = "latest"
ripgrep = "latest"
ruff = "latest"
sd = "latest"
starship = "latest"
tokei = "latest"
typst = "latest"
uv = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"

[settings]
experimental = false
idiomatic_version_file_enable_tools = ["python", "node"]
